export const browserCoreExamples = [
  "must-b browser status",
  "must-b browser start",
  "must-b browser stop",
  "must-b browser tabs",
  "must-b browser open https://example.com",
  "must-b browser focus abcd1234",
  "must-b browser close abcd1234",
  "must-b browser screenshot",
  "must-b browser screenshot --full-page",
  "must-b browser screenshot --ref 12",
  "must-b browser snapshot",
  "must-b browser snapshot --format aria --limit 200",
  "must-b browser snapshot --efficient",
  "must-b browser snapshot --labels",
];

export const browserActionExamples = [
  "must-b browser navigate https://example.com",
  "must-b browser resize 1280 720",
  "must-b browser click 12 --double",
  'must-b browser type 23 "hello" --submit',
  "must-b browser press Enter",
  "must-b browser hover 44",
  "must-b browser drag 10 11",
  "must-b browser select 9 OptionA OptionB",
  "must-b browser upload /tmp/must-b/uploads/file.pdf",
  'must-b browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "must-b browser dialog --accept",
  'must-b browser wait --text "Done"',
  "must-b browser evaluate --fn '(el) => el.textContent' --ref 7",
  "must-b browser console --level error",
  "must-b browser pdf",
];
