apiVersion: v1
kind: Service
metadata:
  name: must-b
  labels:
    app: must-b
spec:
  type: ClusterIP
  selector:
    app: must-b
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
