/**
 * ProjectIntelligence — workspace insight + auto-documentation controller
 *
 * Subsystems:
 *   WorkspaceWatcher  — detects meaningful file changes
 *   SummaryEngine     — periodic project summaries → LTM semantic memory
 *   Insight Injection — "whisper" events to dashboard before first chat
 *   Auto-Documentation — CHANGELOG.md generation from PIPELINE.md + LTM
 *
 * Events emitted:
 *   'whisper'  { message, filePath?, ts }   — proactive insight for the dashboard
 *
 * Wire-up (src/index.ts):
 *   const pi = new ProjectIntelligence({ root, workspaceRoot, ltm, logger });
 *   apiServer.attachIntelligence(pi);
 *   pi.start();
 */
import { EventEmitter }      from 'events';
import fs                    from 'fs';
import path                  from 'path';
import winston               from 'winston';
import { WorkspaceWatcher }  from './workspace-watcher.js';
import { SummaryEngine }     from './summary-engine.js';
import type { LTMController }  from '../memory/ltm.js';
import type { FileChangeEvent } from './workspace-watcher.js';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface WhisperEvent {
  message:   string;
  filePath?: string;
  ts:        number;
}

// ── Insight heuristics ────────────────────────────────────────────────────────

/**
 * Fast static analysis — returns a whisper message if a potential issue
 * or noteworthy change is found in the file content. Returns null otherwise.
 */
function analyzeFile(filePath: string): string | null {
  let content = '';
  try { content = fs.readFileSync(filePath, 'utf-8'); }
  catch { return null; }

  const base = path.basename(filePath);

  // TypeScript / JavaScript: look for obvious red flags
  if (/\.(ts|tsx|js|jsx)$/.test(filePath)) {
    if (/\bconsole\.error\s*\(/.test(content))
      return `${base} içinde yakalanmamış console.error tespit ettim.`;
    if (/TODO:|FIXME:|HACK:|XXX:/.test(content))
      return `${base} içinde çözüme kavuşturulamamış TODO/FIXME notları var.`;
    if (/\/\/ @ts-ignore/.test(content))
      return `${base} içinde @ts-ignore direktifi kullanılmış — tür güvenliği atlanıyor.`;
    if (/throw new Error\(['"]\s*['"]\)/.test(content))
      return `${base} içinde boş hata mesajı fırlatılıyor.`;
  }

  // package.json: new dependency alert
  if (base === 'package.json') {
    try {
      const pkg = JSON.parse(content) as {
        dependencies?: Record<string, string>;
        devDependencies?: Record<string, string>;
      };
      const deps = Object.keys({ ...pkg.dependencies, ...pkg.devDependencies });
      if (deps.length > 0)
        return `package.json güncellendi — ${deps.length} bağımlılık mevcut. Son eklentiler: ${deps.slice(-3).join(', ')}.`;
    } catch {
      return `package.json parse edilemiyor — JSON formatı bozuk olabilir.`;
    }
  }

  // README: content length drop
  if (/^readme(\.\w+)?$/i.test(base)) {
    const lines = content.split('\n').length;
    if (lines < 5)
      return `README güncellendi ama çok kısa (${lines} satır) — dokümantasyon eksik olabilir.`;
  }

  return null;
}

// ── Changelog generator ───────────────────────────────────────────────────────

function generateChangelog(root: string, ltm: LTMController): string {
  const pipelinePath = path.join(root, 'PIPELINE.md');
  let pipeline = '';
  try { pipeline = fs.readFileSync(pipelinePath, 'utf-8'); }
  catch { pipeline = '(PIPELINE.md bulunamadı)'; }

  // Extract deployed sprint entries from PIPELINE.md
  const deployedLines = pipeline
    .split('\n')
    .filter(l => /DEPLOYED/.test(l) && /\|/.test(l))
    .map(l => {
      const cols = l.split('|').map(c => c.trim()).filter(Boolean);
      return cols.length >= 4 ? `- ${cols[0]}: ${cols[2]} [${cols[3]}]` : null;
    })
    .filter(Boolean) as string[];

  // Pull recent semantic memories tagged with project-context
  const recentCtx = ltm.retrieve('project context workspace', 3, 'semantic')
    .map(e => e.content.slice(0, 200))
    .join('\n\n');

  const date = new Date().toISOString().slice(0, 10);

  const lines = [
    `# CHANGELOG`,
    ``,
    `> Auto-generated by Must-b Project Intelligence on ${date}`,
    `> Source: PIPELINE.md + LTM Semantic Memory`,
    ``,
    `## Deployed Versions`,
    ``,
    ...deployedLines,
    ``,
    `## Project Context Snapshot`,
    ``,
    recentCtx || '_No project context in memory yet._',
    ``,
  ];

  return lines.join('\n');
}

// ── ProjectIntelligence ───────────────────────────────────────────────────────

export class ProjectIntelligence extends EventEmitter {
  private logger:   winston.Logger;
  private root:     string;
  private ltm:      LTMController;
  private watcher:  WorkspaceWatcher;
  private engine:   SummaryEngine;

  // Debounce: don't emit duplicate whispers for the same file
  private recentWhispers = new Map<string, number>();
  private readonly WHISPER_COOLDOWN_MS = 10 * 60 * 1000; // 10 min per file
  // Last whisper — sent to newly connected clients
  private _lastWhisper: WhisperEvent | null = null;
  // Stored handler reference for clean removeListener in stop()
  private _fileChangeHandler: ((ev: FileChangeEvent) => void) | null = null;

  constructor(opts: {
    root:          string;
    workspaceRoot: string;
    ltm:           LTMController;
    logger:        winston.Logger;
  }) {
    super();
    this.root    = opts.root;
    this.ltm     = opts.ltm;
    this.logger  = opts.logger;
    this.watcher = new WorkspaceWatcher(opts.workspaceRoot);
    this.engine  = new SummaryEngine(opts.workspaceRoot, opts.ltm);
  }

  start(): void {
    // Wire workspace watcher → insight analysis
    this._fileChangeHandler = (ev: FileChangeEvent) => this.onFileChange(ev);
    this.watcher.on('fileChange', this._fileChangeHandler);
    this.watcher.start();

    // Start periodic summary engine
    this.engine.start();

    this.logger.info('[Intelligence] Workspace watcher + summary engine active.');
  }

  stop(): void {
    if (this._fileChangeHandler) {
      this.watcher.off('fileChange', this._fileChangeHandler);
      this._fileChangeHandler = null;
    }
    this.watcher.stop();
    this.engine.stop();
  }

  /** Returns the most recent whisper — sent to newly connected Socket.io clients. */
  getLastWhisper(): WhisperEvent | null {
    return this._lastWhisper;
  }

  /**
   * Generate CHANGELOG.md from PIPELINE.md + LTM memory.
   * Writes to <root>/CHANGELOG.md and returns the path.
   */
  generateChangelog(): string {
    const content  = generateChangelog(this.root, this.ltm);
    const outPath  = path.join(this.root, 'CHANGELOG.md');
    fs.writeFileSync(outPath, content, 'utf-8');
    this.logger.info(`[Intelligence] CHANGELOG.md oluşturuldu → ${outPath}`);
    return outPath;
  }

  // ── Private ──────────────────────────────────────────────────────────────

  private onFileChange(ev: FileChangeEvent): void {
    if (ev.op === 'unlink') return;

    const now     = Date.now();
    const lastTs  = this.recentWhispers.get(ev.filePath) ?? 0;
    if (now - lastTs < this.WHISPER_COOLDOWN_MS) return;

    // Run heuristic analysis
    const insight = analyzeFile(ev.filePath);
    if (!insight) return;

    this.recentWhispers.set(ev.filePath, now);

    const whisper: WhisperEvent = {
      message:  `CEO, ${insight} Bakmamı ister misiniz?`,
      filePath: ev.filePath,
      ts:       now,
    };

    this._lastWhisper = whisper;
    this.logger.info(`[Intelligence] Whisper: ${whisper.message}`);
    this.emit('whisper', whisper);

    // Also index the observation into episodic memory
    this.ltm.indexEpisodic(
      `Workspace observation: ${ev.rel}`,
      'completed',
      insight,
    );
  }
}
