/**
 * Plugin Architect (v4.9) — Auto-Plugin Builder
 *
 * Generates, hot-reloads, and manages Node.js / Python plugin scripts.
 * Plugins live in src/plugins/ and are discovered automatically on startup.
 *
 * Public API:
 *   buildPlugin(spec)          → writes plugin file to src/plugins/<name>.{mjs|py}
 *   runPlugin(name)            → spawns the plugin process, returns handle
 *   stopPlugin(name)           → kills running plugin
 *   listPlugins()              → array of installed plugins + status
 *   startHotReload(onReload)   → chokidar watcher on src/plugins/
 *   getPluginEvents()          → EventEmitter for 'pluginOutput'|'pluginError'|'pluginReload'
 */

import fs            from 'fs';
import path          from 'path';
import { spawn }     from 'child_process';
import { EventEmitter } from 'events';
import type { ChildProcess } from 'child_process';

// ── Constants ─────────────────────────────────────────────────────────────

// Resolve plugins dir — MUSTB_ROOT (set by bin) → CJS __dirname → cwd fallback
const _pluginRoot = (() => {
  if (process.env.MUSTB_ROOT) return path.resolve(process.env.MUSTB_ROOT);
  if (typeof __dirname !== 'undefined') return path.resolve(__dirname, '..');
  return process.cwd();
})();
const PLUGINS_DIR = path.join(_pluginRoot, 'src', 'plugins');

// ── Types ─────────────────────────────────────────────────────────────────

export type PluginLang = 'node' | 'python';

export interface PluginSpec {
  name:        string;
  goal:        string;
  lang?:       PluginLang;
  /** Optional extra context lines inserted as comments */
  context?:    string;
  /** Override the generated boilerplate entirely */
  customCode?: string;
}

export interface PluginInfo {
  name:      string;
  lang:      PluginLang;
  filename:  string;
  filePath:  string;
  running:   boolean;
  createdAt: string;
}

// ── Internal state ────────────────────────────────────────────────────────

const pluginEvents = new EventEmitter();
pluginEvents.setMaxListeners(30);

const _running = new Map<string, ChildProcess>();

function ensurePluginsDir() {
  if (!fs.existsSync(PLUGINS_DIR)) fs.mkdirSync(PLUGINS_DIR, { recursive: true });
}

// ── Code generator ────────────────────────────────────────────────────────

function generateNodePlugin(spec: PluginSpec): string {
  const { name, goal, context } = spec;
  const ctx = context ? `// Context:\n// ${context.split('\n').join('\n// ')}\n` : '';
  return `/**
 * Plugin: ${name}
 * Goal: ${goal}
 * Generated by Must-b Plugin Architect (v4.9)
 * ${new Date().toISOString()}
 */
${ctx}
import { EventEmitter } from 'events';

const events = new EventEmitter();

// ── Plugin main ────────────────────────────────────────────────────────────

async function run() {
  console.log('[Plugin:${name}] Starting…');

  // TODO: Implement plugin logic for: ${goal}
  // Example: poll an API, process files, integrate a service, etc.

  // Report status back to Must-b host via stdout JSON
  const report = (data) => process.stdout.write(JSON.stringify({ plugin: '${name}', ...data }) + '\\n');

  report({ event: 'started', goal: '${goal}', ts: Date.now() });

  // Graceful shutdown
  process.on('SIGTERM', () => {
    report({ event: 'stopped', ts: Date.now() });
    process.exit(0);
  });

  // Keep alive — replace with your actual logic
  setInterval(() => {
    report({ event: 'heartbeat', ts: Date.now() });
  }, 30_000);
}

run().catch(err => {
  process.stderr.write(JSON.stringify({ plugin: '${name}', event: 'error', message: err.message }) + '\\n');
  process.exit(1);
});
`;
}

function generatePythonPlugin(spec: PluginSpec): string {
  const { name, goal, context } = spec;
  const ctx = context ? `# Context:\n# ${context.split('\n').join('\n# ')}\n` : '';
  return `#!/usr/bin/env python3
"""
Plugin: ${name}
Goal: ${goal}
Generated by Must-b Plugin Architect (v4.9)
${new Date().toISOString()}
"""
${ctx}
import sys
import json
import time
import signal

PLUGIN_NAME = "${name}"

def report(data: dict):
    """Send structured status line to Must-b host."""
    payload = {"plugin": PLUGIN_NAME, **data}
    print(json.dumps(payload), flush=True)

def shutdown(signum, frame):
    report({"event": "stopped", "ts": int(time.time() * 1000)})
    sys.exit(0)

signal.signal(signal.SIGTERM, shutdown)

def run():
    report({"event": "started", "goal": "${goal}", "ts": int(time.time() * 1000)})

    # TODO: Implement plugin logic for: ${goal}
    # Example: process data, call external APIs, monitor resources, etc.

    while True:
        time.sleep(30)
        report({"event": "heartbeat", "ts": int(time.time() * 1000)})

if __name__ == "__main__":
    try:
        run()
    except Exception as e:
        report({"event": "error", "message": str(e)})
        sys.exit(1)
`;
}

// ── Public API ────────────────────────────────────────────────────────────

/**
 * Generate and write a plugin file to src/plugins/.
 * Returns the absolute path of the written file.
 */
export function buildPlugin(spec: PluginSpec): PluginInfo {
  ensurePluginsDir();

  const lang     = spec.lang ?? 'node';
  const safeName = spec.name.replace(/[^a-zA-Z0-9_-]/g, '_');
  const ext      = lang === 'python' ? 'py' : 'mjs';
  const filename  = `${safeName}.${ext}`;
  const filePath  = path.join(PLUGINS_DIR, filename);

  const code = spec.customCode
    ? spec.customCode
    : lang === 'python'
      ? generatePythonPlugin({ ...spec, name: safeName })
      : generateNodePlugin({ ...spec, name: safeName });

  fs.writeFileSync(filePath, code, 'utf8');

  pluginEvents.emit('pluginBuilt', { name: safeName, lang, filePath, ts: Date.now() });

  return {
    name:      safeName,
    lang,
    filename,
    filePath,
    running:   _running.has(safeName),
    createdAt: new Date().toISOString(),
  };
}

/**
 * Spawn a plugin process and attach stdout/stderr listeners.
 * Returns the ChildProcess (or null if already running).
 */
export function runPlugin(name: string): ChildProcess | null {
  ensurePluginsDir();
  if (_running.has(name)) return _running.get(name)!;

  // Try .mjs first, then .py
  let filePath: string | null = null;
  let lang: PluginLang = 'node';

  const mjsPath = path.join(PLUGINS_DIR, `${name}.mjs`);
  const pyPath  = path.join(PLUGINS_DIR, `${name}.py`);

  if (fs.existsSync(mjsPath)) { filePath = mjsPath; lang = 'node'; }
  else if (fs.existsSync(pyPath)) { filePath = pyPath; lang = 'python'; }

  if (!filePath) {
    pluginEvents.emit('pluginError', { name, message: 'Plugin file not found', ts: Date.now() });
    return null;
  }

  const cmd  = lang === 'python' ? 'python3' : 'node';
  const args = [filePath];
  const proc = spawn(cmd, args, { stdio: ['ignore', 'pipe', 'pipe'] });

  proc.stdout?.on('data', (chunk: Buffer) => {
    const lines = chunk.toString().split('\n').filter(Boolean);
    for (const line of lines) {
      try {
        const data = JSON.parse(line);
        pluginEvents.emit('pluginOutput', data);
      } catch {
        pluginEvents.emit('pluginOutput', { plugin: name, event: 'stdout', raw: line });
      }
    }
  });

  proc.stderr?.on('data', (chunk: Buffer) => {
    pluginEvents.emit('pluginError', { name, message: chunk.toString().trim(), ts: Date.now() });
  });

  proc.on('exit', (code) => {
    _running.delete(name);
    pluginEvents.emit('pluginOutput', { plugin: name, event: 'exited', code, ts: Date.now() });
  });

  _running.set(name, proc);
  pluginEvents.emit('pluginOutput', { plugin: name, event: 'launched', lang, ts: Date.now() });

  return proc;
}

/**
 * Kill a running plugin process.
 */
export function stopPlugin(name: string): boolean {
  const proc = _running.get(name);
  if (!proc) return false;
  proc.kill('SIGTERM');
  _running.delete(name);
  return true;
}

/**
 * List all installed plugins with their running status.
 */
export function listPlugins(): PluginInfo[] {
  ensurePluginsDir();
  const infos: PluginInfo[] = [];
  try {
    for (const entry of fs.readdirSync(PLUGINS_DIR)) {
      const ext = path.extname(entry).toLowerCase();
      if (ext !== '.mjs' && ext !== '.py') continue;
      const lang: PluginLang = ext === '.py' ? 'python' : 'node';
      const name = path.basename(entry, ext);
      const filePath = path.join(PLUGINS_DIR, entry);
      const stat = fs.statSync(filePath);
      infos.push({
        name,
        lang,
        filename: entry,
        filePath,
        running:  _running.has(name),
        createdAt: stat.birthtime.toISOString(),
      });
    }
  } catch { /* empty */ }
  return infos;
}

/**
 * Watch src/plugins/ for file changes and auto-reload affected plugins.
 * Calls onReload(name) after reloading.
 */
export async function startHotReload(onReload?: (name: string) => void): Promise<void> {
  ensurePluginsDir();
  const { default: chokidar } = await import('chokidar');

  const watcher = chokidar.watch(PLUGINS_DIR, {
    ignoreInitial: true,
    awaitWriteFinish: { stabilityThreshold: 400, pollInterval: 100 },
  });

  const reload = (filePath: string) => {
    const ext  = path.extname(filePath).toLowerCase();
    if (ext !== '.mjs' && ext !== '.py') return;
    const name = path.basename(filePath, ext);

    // If it was running, restart it
    if (_running.has(name)) {
      stopPlugin(name);
      setTimeout(() => runPlugin(name), 500);
    }

    pluginEvents.emit('pluginReload', { name, filePath, ts: Date.now() });
    onReload?.(name);
  };

  watcher.on('change', reload);
  watcher.on('add',    reload);
}

/** EventEmitter for plugin lifecycle events */
export function getPluginEvents(): EventEmitter {
  return pluginEvents;
}
